#!/usr/bin/env python
# -*- encoding:utf8 -*-

import sys
import os.path as path

if sys.platform == "win32":
    import msvcrt, os
    msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
    msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)

sys.stdout = open("test.bin", 'wb')

def main():
    plugin_require_bin = sys.stdin.read()
    sys.stdout.write(plugin_require_bin)

if __name__ == "__main__":
    main()

